# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myjenkins-pvc
spec:
  storageClassName: jenkinslocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myjenkins-pv
spec:
  storageClassName: jenkinslocalstorage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/jenkins/data/"
    type: DirectoryOrCreate
